// Paleta de cores de domínio: usada por projetos e eventos da agenda. value = hex #rrggbb.
export const projectColorOptions = [
	{ value: "#ef4444", label: "Vermelho" },
	{ value: "#f97316", label: "Laranja" },
	{ value: "#f59e0b", label: "Âmbar" },
	{ value: "#eab308", label: "Amarelo" },
	{ value: "#84cc16", label: "Lima" },
	{ value: "#22c55e", label: "Verde" },
	{ value: "#10b981", label: "Esmeralda" },
	{ value: "#14b8a6", label: "Turquesa" },
	{ value: "#06b6d4", label: "Ciano" },
	{ value: "#0ea5e9", label: "Azul claro" },
	{ value: "#3b82f6", label: "Azul" },
	{ value: "#6366f1", label: "Índigo" },
	{ value: "#8b5cf6", label: "Violeta" },
	{ value: "#a855f7", label: "Roxo" },
	{ value: "#d946ef", label: "Fúcsia" },
	{ value: "#ec4899", label: "Rosa" },
	{ value: "#f43f5e", label: "Rose" },
	{ value: "#fb7185", label: "Rosa claro" },
	{ value: "#fda4af", label: "Rosado" },
	{ value: "#22d3ee", label: "Ciano vivo" },
	{ value: "#38bdf8", label: "Sky" },
	{ value: "#60a5fa", label: "Azul médio" },
	{ value: "#7c3aed", label: "Roxo profundo" },
	{ value: "#9333ea", label: "Violeta intenso" },
	{ value: "#a3e635", label: "Verde limão" },
	{ value: "#4ade80", label: "Verde claro" },
];

export const defaultProjectColor = projectColorOptions[5]?.value ?? "#22c55e";
