/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSistemaRouteImport } from './routes/_app/sistema'
import { Route as AppKwTerminalRouteImport } from './routes/_app/kw-terminal'
import { Route as AppFontesRouteImport } from './routes/_app/fontes'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppVaultIndexRouteImport } from './routes/_app/vault/index'
import { Route as AppTarefasIndexRouteImport } from './routes/_app/tarefas/index'
import { Route as AppSkillsIndexRouteImport } from './routes/_app/skills/index'
import { Route as AppPromptsIndexRouteImport } from './routes/_app/prompts/index'
import { Route as AppProjetosIndexRouteImport } from './routes/_app/projetos/index'
import { Route as AppMostruarioIndexRouteImport } from './routes/_app/mostruario/index'
import { Route as AppMediaIndexRouteImport } from './routes/_app/media/index'
import { Route as AppAgentsIndexRouteImport } from './routes/_app/agents/index'
import { Route as AppAgendaIndexRouteImport } from './routes/_app/agenda/index'
import { Route as AppVaultFileNameIndexRouteImport } from './routes/_app/vault/$fileName/index'
import { Route as AppTarefasTaskIdIndexRouteImport } from './routes/_app/tarefas/$taskId/index'
import { Route as AppSkillsSlugIndexRouteImport } from './routes/_app/skills/$slug/index'
import { Route as AppProjetosNovoIndexRouteImport } from './routes/_app/projetos/novo/index'
import { Route as AppProjetosProjetoIdIndexRouteImport } from './routes/_app/projetos/$projetoId/index'
import { Route as AppMediaFileNameIndexRouteImport } from './routes/_app/media/$fileName/index'
import { Route as AppAgentsSlugIndexRouteImport } from './routes/_app/agents/$slug/index'
import { Route as AppTarefasTaskIdFileRouteImport } from './routes/_app/tarefas/$taskId/$file'
import { Route as AppProjetosProjetoIdDocsSplatRouteImport } from './routes/_app/projetos/$projetoId/docs/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSistemaRoute = AppSistemaRouteImport.update({
  id: '/sistema',
  path: '/sistema',
  getParentRoute: () => AppRoute,
} as any)
const AppKwTerminalRoute = AppKwTerminalRouteImport.update({
  id: '/kw-terminal',
  path: '/kw-terminal',
  getParentRoute: () => AppRoute,
} as any)
const AppFontesRoute = AppFontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultIndexRoute = AppVaultIndexRouteImport.update({
  id: '/vault/',
  path: '/vault/',
  getParentRoute: () => AppRoute,
} as any)
const AppTarefasIndexRoute = AppTarefasIndexRouteImport.update({
  id: '/tarefas/',
  path: '/tarefas/',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsIndexRoute = AppSkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => AppRoute,
} as any)
const AppPromptsIndexRoute = AppPromptsIndexRouteImport.update({
  id: '/prompts/',
  path: '/prompts/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosIndexRoute = AppProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => AppRoute,
} as any)
const AppMostruarioIndexRoute = AppMostruarioIndexRouteImport.update({
  id: '/mostruario/',
  path: '/mostruario/',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaIndexRoute = AppMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsIndexRoute = AppAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaIndexRoute = AppAgendaIndexRouteImport.update({
  id: '/agenda/',
  path: '/agenda/',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultFileNameIndexRoute = AppVaultFileNameIndexRouteImport.update({
  id: '/vault/$fileName/',
  path: '/vault/$fileName/',
  getParentRoute: () => AppRoute,
} as any)
const AppTarefasTaskIdIndexRoute = AppTarefasTaskIdIndexRouteImport.update({
  id: '/tarefas/$taskId/',
  path: '/tarefas/$taskId/',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsSlugIndexRoute = AppSkillsSlugIndexRouteImport.update({
  id: '/skills/$slug/',
  path: '/skills/$slug/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosNovoIndexRoute = AppProjetosNovoIndexRouteImport.update({
  id: '/projetos/novo/',
  path: '/projetos/novo/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosProjetoIdIndexRoute =
  AppProjetosProjetoIdIndexRouteImport.update({
    id: '/projetos/$projetoId/',
    path: '/projetos/$projetoId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppMediaFileNameIndexRoute = AppMediaFileNameIndexRouteImport.update({
  id: '/media/$fileName/',
  path: '/media/$fileName/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsSlugIndexRoute = AppAgentsSlugIndexRouteImport.update({
  id: '/agents/$slug/',
  path: '/agents/$slug/',
  getParentRoute: () => AppRoute,
} as any)
const AppTarefasTaskIdFileRoute = AppTarefasTaskIdFileRouteImport.update({
  id: '/tarefas/$taskId/$file',
  path: '/tarefas/$taskId/$file',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosProjetoIdDocsSplatRoute =
  AppProjetosProjetoIdDocsSplatRouteImport.update({
    id: '/projetos/$projetoId/docs/$',
    path: '/projetos/$projetoId/docs/$',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/fontes': typeof AppFontesRoute
  '/kw-terminal': typeof AppKwTerminalRoute
  '/sistema': typeof AppSistemaRoute
  '/agenda/': typeof AppAgendaIndexRoute
  '/agents/': typeof AppAgentsIndexRoute
  '/media/': typeof AppMediaIndexRoute
  '/mostruario/': typeof AppMostruarioIndexRoute
  '/projetos/': typeof AppProjetosIndexRoute
  '/prompts/': typeof AppPromptsIndexRoute
  '/skills/': typeof AppSkillsIndexRoute
  '/tarefas/': typeof AppTarefasIndexRoute
  '/vault/': typeof AppVaultIndexRoute
  '/tarefas/$taskId/$file': typeof AppTarefasTaskIdFileRoute
  '/agents/$slug/': typeof AppAgentsSlugIndexRoute
  '/media/$fileName/': typeof AppMediaFileNameIndexRoute
  '/projetos/$projetoId/': typeof AppProjetosProjetoIdIndexRoute
  '/projetos/novo/': typeof AppProjetosNovoIndexRoute
  '/skills/$slug/': typeof AppSkillsSlugIndexRoute
  '/tarefas/$taskId/': typeof AppTarefasTaskIdIndexRoute
  '/vault/$fileName/': typeof AppVaultFileNameIndexRoute
  '/projetos/$projetoId/docs/$': typeof AppProjetosProjetoIdDocsSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/fontes': typeof AppFontesRoute
  '/kw-terminal': typeof AppKwTerminalRoute
  '/sistema': typeof AppSistemaRoute
  '/': typeof AppIndexRoute
  '/agenda': typeof AppAgendaIndexRoute
  '/agents': typeof AppAgentsIndexRoute
  '/media': typeof AppMediaIndexRoute
  '/mostruario': typeof AppMostruarioIndexRoute
  '/projetos': typeof AppProjetosIndexRoute
  '/prompts': typeof AppPromptsIndexRoute
  '/skills': typeof AppSkillsIndexRoute
  '/tarefas': typeof AppTarefasIndexRoute
  '/vault': typeof AppVaultIndexRoute
  '/tarefas/$taskId/$file': typeof AppTarefasTaskIdFileRoute
  '/agents/$slug': typeof AppAgentsSlugIndexRoute
  '/media/$fileName': typeof AppMediaFileNameIndexRoute
  '/projetos/$projetoId': typeof AppProjetosProjetoIdIndexRoute
  '/projetos/novo': typeof AppProjetosNovoIndexRoute
  '/skills/$slug': typeof AppSkillsSlugIndexRoute
  '/tarefas/$taskId': typeof AppTarefasTaskIdIndexRoute
  '/vault/$fileName': typeof AppVaultFileNameIndexRoute
  '/projetos/$projetoId/docs/$': typeof AppProjetosProjetoIdDocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/fontes': typeof AppFontesRoute
  '/_app/kw-terminal': typeof AppKwTerminalRoute
  '/_app/sistema': typeof AppSistemaRoute
  '/_app/': typeof AppIndexRoute
  '/_app/agenda/': typeof AppAgendaIndexRoute
  '/_app/agents/': typeof AppAgentsIndexRoute
  '/_app/media/': typeof AppMediaIndexRoute
  '/_app/mostruario/': typeof AppMostruarioIndexRoute
  '/_app/projetos/': typeof AppProjetosIndexRoute
  '/_app/prompts/': typeof AppPromptsIndexRoute
  '/_app/skills/': typeof AppSkillsIndexRoute
  '/_app/tarefas/': typeof AppTarefasIndexRoute
  '/_app/vault/': typeof AppVaultIndexRoute
  '/_app/tarefas/$taskId/$file': typeof AppTarefasTaskIdFileRoute
  '/_app/agents/$slug/': typeof AppAgentsSlugIndexRoute
  '/_app/media/$fileName/': typeof AppMediaFileNameIndexRoute
  '/_app/projetos/$projetoId/': typeof AppProjetosProjetoIdIndexRoute
  '/_app/projetos/novo/': typeof AppProjetosNovoIndexRoute
  '/_app/skills/$slug/': typeof AppSkillsSlugIndexRoute
  '/_app/tarefas/$taskId/': typeof AppTarefasTaskIdIndexRoute
  '/_app/vault/$fileName/': typeof AppVaultFileNameIndexRoute
  '/_app/projetos/$projetoId/docs/$': typeof AppProjetosProjetoIdDocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/fontes'
    | '/kw-terminal'
    | '/sistema'
    | '/agenda/'
    | '/agents/'
    | '/media/'
    | '/mostruario/'
    | '/projetos/'
    | '/prompts/'
    | '/skills/'
    | '/tarefas/'
    | '/vault/'
    | '/tarefas/$taskId/$file'
    | '/agents/$slug/'
    | '/media/$fileName/'
    | '/projetos/$projetoId/'
    | '/projetos/novo/'
    | '/skills/$slug/'
    | '/tarefas/$taskId/'
    | '/vault/$fileName/'
    | '/projetos/$projetoId/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/configuracoes'
    | '/fontes'
    | '/kw-terminal'
    | '/sistema'
    | '/'
    | '/agenda'
    | '/agents'
    | '/media'
    | '/mostruario'
    | '/projetos'
    | '/prompts'
    | '/skills'
    | '/tarefas'
    | '/vault'
    | '/tarefas/$taskId/$file'
    | '/agents/$slug'
    | '/media/$fileName'
    | '/projetos/$projetoId'
    | '/projetos/novo'
    | '/skills/$slug'
    | '/tarefas/$taskId'
    | '/vault/$fileName'
    | '/projetos/$projetoId/docs/$'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/configuracoes'
    | '/_app/fontes'
    | '/_app/kw-terminal'
    | '/_app/sistema'
    | '/_app/'
    | '/_app/agenda/'
    | '/_app/agents/'
    | '/_app/media/'
    | '/_app/mostruario/'
    | '/_app/projetos/'
    | '/_app/prompts/'
    | '/_app/skills/'
    | '/_app/tarefas/'
    | '/_app/vault/'
    | '/_app/tarefas/$taskId/$file'
    | '/_app/agents/$slug/'
    | '/_app/media/$fileName/'
    | '/_app/projetos/$projetoId/'
    | '/_app/projetos/novo/'
    | '/_app/skills/$slug/'
    | '/_app/tarefas/$taskId/'
    | '/_app/vault/$fileName/'
    | '/_app/projetos/$projetoId/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sistema': {
      id: '/_app/sistema'
      path: '/sistema'
      fullPath: '/sistema'
      preLoaderRoute: typeof AppSistemaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kw-terminal': {
      id: '/_app/kw-terminal'
      path: '/kw-terminal'
      fullPath: '/kw-terminal'
      preLoaderRoute: typeof AppKwTerminalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fontes': {
      id: '/_app/fontes'
      path: '/fontes'
      fullPath: '/fontes'
      preLoaderRoute: typeof AppFontesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vault/': {
      id: '/_app/vault/'
      path: '/vault'
      fullPath: '/vault/'
      preLoaderRoute: typeof AppVaultIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tarefas/': {
      id: '/_app/tarefas/'
      path: '/tarefas'
      fullPath: '/tarefas/'
      preLoaderRoute: typeof AppTarefasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills/': {
      id: '/_app/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof AppSkillsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prompts/': {
      id: '/_app/prompts/'
      path: '/prompts'
      fullPath: '/prompts/'
      preLoaderRoute: typeof AppPromptsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projetos/': {
      id: '/_app/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof AppProjetosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mostruario/': {
      id: '/_app/mostruario/'
      path: '/mostruario'
      fullPath: '/mostruario/'
      preLoaderRoute: typeof AppMostruarioIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/media/': {
      id: '/_app/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof AppMediaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/': {
      id: '/_app/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AppAgentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda/': {
      id: '/_app/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AppAgendaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vault/$fileName/': {
      id: '/_app/vault/$fileName/'
      path: '/vault/$fileName'
      fullPath: '/vault/$fileName/'
      preLoaderRoute: typeof AppVaultFileNameIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tarefas/$taskId/': {
      id: '/_app/tarefas/$taskId/'
      path: '/tarefas/$taskId'
      fullPath: '/tarefas/$taskId/'
      preLoaderRoute: typeof AppTarefasTaskIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills/$slug/': {
      id: '/_app/skills/$slug/'
      path: '/skills/$slug'
      fullPath: '/skills/$slug/'
      preLoaderRoute: typeof AppSkillsSlugIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projetos/novo/': {
      id: '/_app/projetos/novo/'
      path: '/projetos/novo'
      fullPath: '/projetos/novo/'
      preLoaderRoute: typeof AppProjetosNovoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projetos/$projetoId/': {
      id: '/_app/projetos/$projetoId/'
      path: '/projetos/$projetoId'
      fullPath: '/projetos/$projetoId/'
      preLoaderRoute: typeof AppProjetosProjetoIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/media/$fileName/': {
      id: '/_app/media/$fileName/'
      path: '/media/$fileName'
      fullPath: '/media/$fileName/'
      preLoaderRoute: typeof AppMediaFileNameIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$slug/': {
      id: '/_app/agents/$slug/'
      path: '/agents/$slug'
      fullPath: '/agents/$slug/'
      preLoaderRoute: typeof AppAgentsSlugIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tarefas/$taskId/$file': {
      id: '/_app/tarefas/$taskId/$file'
      path: '/tarefas/$taskId/$file'
      fullPath: '/tarefas/$taskId/$file'
      preLoaderRoute: typeof AppTarefasTaskIdFileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projetos/$projetoId/docs/$': {
      id: '/_app/projetos/$projetoId/docs/$'
      path: '/projetos/$projetoId/docs/$'
      fullPath: '/projetos/$projetoId/docs/$'
      preLoaderRoute: typeof AppProjetosProjetoIdDocsSplatRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppFontesRoute: typeof AppFontesRoute
  AppKwTerminalRoute: typeof AppKwTerminalRoute
  AppSistemaRoute: typeof AppSistemaRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAgendaIndexRoute: typeof AppAgendaIndexRoute
  AppAgentsIndexRoute: typeof AppAgentsIndexRoute
  AppMediaIndexRoute: typeof AppMediaIndexRoute
  AppMostruarioIndexRoute: typeof AppMostruarioIndexRoute
  AppProjetosIndexRoute: typeof AppProjetosIndexRoute
  AppPromptsIndexRoute: typeof AppPromptsIndexRoute
  AppSkillsIndexRoute: typeof AppSkillsIndexRoute
  AppTarefasIndexRoute: typeof AppTarefasIndexRoute
  AppVaultIndexRoute: typeof AppVaultIndexRoute
  AppTarefasTaskIdFileRoute: typeof AppTarefasTaskIdFileRoute
  AppAgentsSlugIndexRoute: typeof AppAgentsSlugIndexRoute
  AppMediaFileNameIndexRoute: typeof AppMediaFileNameIndexRoute
  AppProjetosProjetoIdIndexRoute: typeof AppProjetosProjetoIdIndexRoute
  AppProjetosNovoIndexRoute: typeof AppProjetosNovoIndexRoute
  AppSkillsSlugIndexRoute: typeof AppSkillsSlugIndexRoute
  AppTarefasTaskIdIndexRoute: typeof AppTarefasTaskIdIndexRoute
  AppVaultFileNameIndexRoute: typeof AppVaultFileNameIndexRoute
  AppProjetosProjetoIdDocsSplatRoute: typeof AppProjetosProjetoIdDocsSplatRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppFontesRoute: AppFontesRoute,
  AppKwTerminalRoute: AppKwTerminalRoute,
  AppSistemaRoute: AppSistemaRoute,
  AppIndexRoute: AppIndexRoute,
  AppAgendaIndexRoute: AppAgendaIndexRoute,
  AppAgentsIndexRoute: AppAgentsIndexRoute,
  AppMediaIndexRoute: AppMediaIndexRoute,
  AppMostruarioIndexRoute: AppMostruarioIndexRoute,
  AppProjetosIndexRoute: AppProjetosIndexRoute,
  AppPromptsIndexRoute: AppPromptsIndexRoute,
  AppSkillsIndexRoute: AppSkillsIndexRoute,
  AppTarefasIndexRoute: AppTarefasIndexRoute,
  AppVaultIndexRoute: AppVaultIndexRoute,
  AppTarefasTaskIdFileRoute: AppTarefasTaskIdFileRoute,
  AppAgentsSlugIndexRoute: AppAgentsSlugIndexRoute,
  AppMediaFileNameIndexRoute: AppMediaFileNameIndexRoute,
  AppProjetosProjetoIdIndexRoute: AppProjetosProjetoIdIndexRoute,
  AppProjetosNovoIndexRoute: AppProjetosNovoIndexRoute,
  AppSkillsSlugIndexRoute: AppSkillsSlugIndexRoute,
  AppTarefasTaskIdIndexRoute: AppTarefasTaskIdIndexRoute,
  AppVaultFileNameIndexRoute: AppVaultFileNameIndexRoute,
  AppProjetosProjetoIdDocsSplatRoute: AppProjetosProjetoIdDocsSplatRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
