/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppFontesRouteImport } from './routes/_app/fontes'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppVaultIndexRouteImport } from './routes/_app/vault/index'
import { Route as AppTarefasIndexRouteImport } from './routes/_app/tarefas/index'
import { Route as AppSkillsIndexRouteImport } from './routes/_app/skills/index'
import { Route as AppProjetosIndexRouteImport } from './routes/_app/projetos/index'
import { Route as AppAgendaIndexRouteImport } from './routes/_app/agenda/index'
import { Route as AppVaultFileNameIndexRouteImport } from './routes/_app/vault/$fileName/index'
import { Route as AppTarefasTaskIdIndexRouteImport } from './routes/_app/tarefas/$taskId/index'
import { Route as AppProjetosNovoIndexRouteImport } from './routes/_app/projetos/novo/index'
import { Route as AppProjetosProjetoIdIndexRouteImport } from './routes/_app/projetos/$projetoId/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppFontesRoute = AppFontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultIndexRoute = AppVaultIndexRouteImport.update({
  id: '/vault/',
  path: '/vault/',
  getParentRoute: () => AppRoute,
} as any)
const AppTarefasIndexRoute = AppTarefasIndexRouteImport.update({
  id: '/tarefas/',
  path: '/tarefas/',
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsIndexRoute = AppSkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosIndexRoute = AppProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaIndexRoute = AppAgendaIndexRouteImport.update({
  id: '/agenda/',
  path: '/agenda/',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultFileNameIndexRoute = AppVaultFileNameIndexRouteImport.update({
  id: '/vault/$fileName/',
  path: '/vault/$fileName/',
  getParentRoute: () => AppRoute,
} as any)
const AppTarefasTaskIdIndexRoute = AppTarefasTaskIdIndexRouteImport.update({
  id: '/tarefas/$taskId/',
  path: '/tarefas/$taskId/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosNovoIndexRoute = AppProjetosNovoIndexRouteImport.update({
  id: '/projetos/novo/',
  path: '/projetos/novo/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosProjetoIdIndexRoute =
  AppProjetosProjetoIdIndexRouteImport.update({
    id: '/projetos/$projetoId/',
    path: '/projetos/$projetoId/',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/fontes': typeof AppFontesRoute
  '/agenda/': typeof AppAgendaIndexRoute
  '/projetos/': typeof AppProjetosIndexRoute
  '/skills/': typeof AppSkillsIndexRoute
  '/tarefas/': typeof AppTarefasIndexRoute
  '/vault/': typeof AppVaultIndexRoute
  '/projetos/$projetoId/': typeof AppProjetosProjetoIdIndexRoute
  '/projetos/novo/': typeof AppProjetosNovoIndexRoute
  '/tarefas/$taskId/': typeof AppTarefasTaskIdIndexRoute
  '/vault/$fileName/': typeof AppVaultFileNameIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/fontes': typeof AppFontesRoute
  '/': typeof AppIndexRoute
  '/agenda': typeof AppAgendaIndexRoute
  '/projetos': typeof AppProjetosIndexRoute
  '/skills': typeof AppSkillsIndexRoute
  '/tarefas': typeof AppTarefasIndexRoute
  '/vault': typeof AppVaultIndexRoute
  '/projetos/$projetoId': typeof AppProjetosProjetoIdIndexRoute
  '/projetos/novo': typeof AppProjetosNovoIndexRoute
  '/tarefas/$taskId': typeof AppTarefasTaskIdIndexRoute
  '/vault/$fileName': typeof AppVaultFileNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/fontes': typeof AppFontesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/agenda/': typeof AppAgendaIndexRoute
  '/_app/projetos/': typeof AppProjetosIndexRoute
  '/_app/skills/': typeof AppSkillsIndexRoute
  '/_app/tarefas/': typeof AppTarefasIndexRoute
  '/_app/vault/': typeof AppVaultIndexRoute
  '/_app/projetos/$projetoId/': typeof AppProjetosProjetoIdIndexRoute
  '/_app/projetos/novo/': typeof AppProjetosNovoIndexRoute
  '/_app/tarefas/$taskId/': typeof AppTarefasTaskIdIndexRoute
  '/_app/vault/$fileName/': typeof AppVaultFileNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/fontes'
    | '/agenda/'
    | '/projetos/'
    | '/skills/'
    | '/tarefas/'
    | '/vault/'
    | '/projetos/$projetoId/'
    | '/projetos/novo/'
    | '/tarefas/$taskId/'
    | '/vault/$fileName/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/configuracoes'
    | '/fontes'
    | '/'
    | '/agenda'
    | '/projetos'
    | '/skills'
    | '/tarefas'
    | '/vault'
    | '/projetos/$projetoId'
    | '/projetos/novo'
    | '/tarefas/$taskId'
    | '/vault/$fileName'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/configuracoes'
    | '/_app/fontes'
    | '/_app/'
    | '/_app/agenda/'
    | '/_app/projetos/'
    | '/_app/skills/'
    | '/_app/tarefas/'
    | '/_app/vault/'
    | '/_app/projetos/$projetoId/'
    | '/_app/projetos/novo/'
    | '/_app/tarefas/$taskId/'
    | '/_app/vault/$fileName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fontes': {
      id: '/_app/fontes'
      path: '/fontes'
      fullPath: '/fontes'
      preLoaderRoute: typeof AppFontesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vault/': {
      id: '/_app/vault/'
      path: '/vault'
      fullPath: '/vault/'
      preLoaderRoute: typeof AppVaultIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tarefas/': {
      id: '/_app/tarefas/'
      path: '/tarefas'
      fullPath: '/tarefas/'
      preLoaderRoute: typeof AppTarefasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/skills/': {
      id: '/_app/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof AppSkillsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projetos/': {
      id: '/_app/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof AppProjetosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda/': {
      id: '/_app/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AppAgendaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vault/$fileName/': {
      id: '/_app/vault/$fileName/'
      path: '/vault/$fileName'
      fullPath: '/vault/$fileName/'
      preLoaderRoute: typeof AppVaultFileNameIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tarefas/$taskId/': {
      id: '/_app/tarefas/$taskId/'
      path: '/tarefas/$taskId'
      fullPath: '/tarefas/$taskId/'
      preLoaderRoute: typeof AppTarefasTaskIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projetos/novo/': {
      id: '/_app/projetos/novo/'
      path: '/projetos/novo'
      fullPath: '/projetos/novo/'
      preLoaderRoute: typeof AppProjetosNovoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projetos/$projetoId/': {
      id: '/_app/projetos/$projetoId/'
      path: '/projetos/$projetoId'
      fullPath: '/projetos/$projetoId/'
      preLoaderRoute: typeof AppProjetosProjetoIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppFontesRoute: typeof AppFontesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAgendaIndexRoute: typeof AppAgendaIndexRoute
  AppProjetosIndexRoute: typeof AppProjetosIndexRoute
  AppSkillsIndexRoute: typeof AppSkillsIndexRoute
  AppTarefasIndexRoute: typeof AppTarefasIndexRoute
  AppVaultIndexRoute: typeof AppVaultIndexRoute
  AppProjetosProjetoIdIndexRoute: typeof AppProjetosProjetoIdIndexRoute
  AppProjetosNovoIndexRoute: typeof AppProjetosNovoIndexRoute
  AppTarefasTaskIdIndexRoute: typeof AppTarefasTaskIdIndexRoute
  AppVaultFileNameIndexRoute: typeof AppVaultFileNameIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppFontesRoute: AppFontesRoute,
  AppIndexRoute: AppIndexRoute,
  AppAgendaIndexRoute: AppAgendaIndexRoute,
  AppProjetosIndexRoute: AppProjetosIndexRoute,
  AppSkillsIndexRoute: AppSkillsIndexRoute,
  AppTarefasIndexRoute: AppTarefasIndexRoute,
  AppVaultIndexRoute: AppVaultIndexRoute,
  AppProjetosProjetoIdIndexRoute: AppProjetosProjetoIdIndexRoute,
  AppProjetosNovoIndexRoute: AppProjetosNovoIndexRoute,
  AppTarefasTaskIdIndexRoute: AppTarefasTaskIdIndexRoute,
  AppVaultFileNameIndexRoute: AppVaultFileNameIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
